gen:
	/Users/qiaocc/opensource/proj-go/code-generator/generate-groups.sh all \
		github.com/operator-crd/pkg/generated \
		github.com/operator-crd/pkg/apis \
		crd.example.com:v1 \
		--go-header-file=/Users/qiaocc/opensource/proj-go/code-generator/hack/boilerplate.go.txt \
		--output-base ../../
