apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # 集群维度
metadata:
  creationTimestamp: null
  name: ingress-manager-rule
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - list
  - watch
  - create
  - update
  - delete
